### ISSUE TITLE
Add Wildcard operator

### ISSUE THREAD

**Issue by zenorocha** [wedeploy/wedeploy-sdk-swift#23]

**Comment by ipeychev** [comment]
The [PR](https://github.com/wedeploy/wedeploy-sdk-js/pull/243) which implements this in SDK JS is now merged. [Those](https://github.com/wedeploy/engine/pull/932) which adds this functionality in Engine too, so you may go ahead and implement it here too.

**Comment by victorg1991** [comment]
Thanks @ipeychev for the links!  :)
